### ISSUE TITLE
Can't install Spades

### ISSUE THREAD

**Issue by fincaminimo** [rogeriochaves/spades#38]
I've tried to install Spades following the instructions... but it doesn't work.

npm -g install git+https://github.com/rogeriochaves/spades.git
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
/home/arkaitz/.nvm/versions/node/v12.14.0/bin/elm-generate -> /home/arkaitz/.nvm/versions/node/v12.14.0/lib/node_modules/elm-on-spades/bin/elm-generate

> elm@0.19.0 install /home/arkaitz/.nvm/versions/node/v12.14.0/lib/node_modules/elm-on-spades/node_modules/elm
> binwrap-install

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/home/arkaitz/.nvm/versions/node/v12.14.0/lib/node_modules/elm-on-spades/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/arkaitz/.nvm/versions/node/v12.14.0/lib/node_modules/elm-on-spades/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/arkaitz/.nvm/versions/node/v12.14.0/lib/node_modules/elm-on-spades/node_modules/unzip/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elm@0.19.0 install: `binwrap-install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the elm@0.19.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/arkaitz/.npm/_logs/2019-12-20T10_32_10_966Z-debug.log

And the log output:

7479 verbose argv "/home/arkaitz/.nvm/versions/node/v12.14.0/bin/node" "/home/arkaitz/.nvm/versions/node/v12.14.0/bin/npm" "-g" "install" "git+https://github.com/rogeriochaves/spades.git"
7480 verbose node v12.14.0
7481 verbose npm  v6.13.4
7482 error code ELIFECYCLE
7483 error errno 1
7484 error elm@0.19.0 install: `binwrap-install`
7484 error Exit status 1
7485 error Failed at the elm@0.19.0 install script.
7485 error This is probably not a problem with npm. There is likely additional logging output above.
7486 verbose exit [ 1, true ]

**Comment by iho** [comment]
Same error.

**Comment by andys8** [comment]
This might be easily fixed with dependency version bumps in this project.

**Comment by itypesillycode** [comment]
is anyone gonna accept the pull request? can i just work from the pull request?

**Comment by rogeriochaves** [comment]
Sorry for the long delay folks, it is now fixed by #39 and also commit 6f4ba11eadde38d2af206d0b596f60a9ef946daf
